Inherit from 3.2 core instead of 3.0
This is a problem: OSX needs 3.2 core, the rest 3.0. If we... Try
to #ifdef the inheritance, Moc gets awfully confused:

In file included from /Users/boud/master/build/libs/ui/kritaui_automoc.cpp:142:
/Users/boud/master/build/libs/ui/moc_kis_opengl_canvas2.cpp:94:29: error: unknown type name
      'QOpenGLFunctions_3_0'; did you mean 'QOpenGLFunctions'?
        return static_cast< QOpenGLFunctions_3_0*>(const_cast< KisOpenGLCanvas2*>(this));
                            ^~~~~~~~~~~~~~~~~~~~
                            QOpenGLFunctions
/Users/boud/master/krita/libs/ui/opengl/kis_opengl_image_textures.h:34:7: note: 'QOpenGLFunctions' declared here
class QOpenGLFunctions;
      ^
In file included from /Users/boud/master/build/libs/ui/kritaui_automoc.cpp:142:
/Users/boud/master/build/libs/ui/moc_kis_opengl_canvas2.cpp:94:16: error: static_cast from 'KisOpenGLCanvas2 *' to
      'QOpenGLFunctions *', which are not related by inheritance, is not allowed
        return static_cast< QOpenGLFunctions_3_0*>(const_cast< KisOpenGLCanvas2*>(this));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [libs/ui/CMakeFiles/kritaui.dir/kritaui_automoc.cpp.o] Error 1